// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import InsertMatchReducer from "../insert_match_reducer";
import LogAgentDecisionReducer from "../log_agent_decision_reducer";
import UpdateMatchStatusReducer from "../update_match_status_reducer";
import UpdateOrderStatusReducer from "../update_order_status_reducer";
import UpdateRiderLocationReducer from "../update_rider_location_reducer";

export type InsertMatchParams = __Infer<typeof InsertMatchReducer>;
export type LogAgentDecisionParams = __Infer<typeof LogAgentDecisionReducer>;
export type UpdateMatchStatusParams = __Infer<typeof UpdateMatchStatusReducer>;
export type UpdateOrderStatusParams = __Infer<typeof UpdateOrderStatusReducer>;
export type UpdateRiderLocationParams = __Infer<typeof UpdateRiderLocationReducer>;

