// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  matchId: __t.string().primaryKey().name("match_id"),
  riderId: __t.string().name("rider_id"),
  orderIds: __t.string().name("order_ids"),
  platforms: __t.string(),
  overlapScore: __t.u64().name("overlap_score"),
  combinedEarnings: __t.u64().name("combined_earnings"),
  status: __t.string(),
  explanation: __t.string(),
  timestamp: __t.u64(),
});
