// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  decisionId: __t.string().primaryKey().name("decision_id"),
  decision: __t.string(),
  reason: __t.string(),
  overlapScore: __t.u64().name("overlap_score"),
  detourPercent: __t.u64().name("detour_percent"),
  capacity: __t.string(),
  timestamp: __t.u64(),
});
