// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  decisionId: __t.string(),
  decision: __t.string(),
  reason: __t.string(),
  overlapScore: __t.u64(),
  detourPercent: __t.u64(),
  capacity: __t.string(),
  timestamp: __t.u64(),
};
