// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orderId: __t.string().primaryKey().name("order_id"),
  status: __t.string(),
  discountApplied: __t.u64().name("discount_applied"),
  platform: __t.string(),
  savingsMessage: __t.string().name("savings_message"),
  timestamp: __t.u64(),
});
