// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActiveMatch = __t.object("ActiveMatch", {
  matchId: __t.string(),
  riderId: __t.string(),
  orderIds: __t.string(),
  platforms: __t.string(),
  overlapScore: __t.u64(),
  combinedEarnings: __t.u64(),
  status: __t.string(),
  explanation: __t.string(),
  timestamp: __t.u64(),
});
export type ActiveMatch = __Infer<typeof ActiveMatch>;

export const AgentDecision = __t.object("AgentDecision", {
  decisionId: __t.string(),
  decision: __t.string(),
  reason: __t.string(),
  overlapScore: __t.u64(),
  detourPercent: __t.u64(),
  capacity: __t.string(),
  timestamp: __t.u64(),
});
export type AgentDecision = __Infer<typeof AgentDecision>;

export const OrderStatus = __t.object("OrderStatus", {
  orderId: __t.string(),
  status: __t.string(),
  discountApplied: __t.u64(),
  platform: __t.string(),
  savingsMessage: __t.string(),
  timestamp: __t.u64(),
});
export type OrderStatus = __Infer<typeof OrderStatus>;

export const RiderLocation = __t.object("RiderLocation", {
  riderId: __t.string(),
  lat: __t.string(),
  lng: __t.string(),
  currentStopIndex: __t.u64(),
  timestamp: __t.u64(),
});
export type RiderLocation = __Infer<typeof RiderLocation>;

